[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts', "foundry-devops=lib/foundry-devops/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
